export const USER_ROLES = {
  CITIZEN: "citizen",
  STUDENT: "student",
  FACULTY: "faculty",
  INDUSTRY: "industry",
  GOVERNMENT: "government",
  ADMIN: "admin",
} as const;

export const USER_STATUSES = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  SUSPENDED: "SUSPENDED",
  BANNED: "BANNED",
} as const;

export const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  USER_LOGOUT: "USER_LOGOUT",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
} as const;

export const NOTIFICATION_TYPES = {
  SYSTEM: "SYSTEM",
  ALERT: "ALERT",
  CHALLENGE_UPDATE: "CHALLENGE_UPDATE",
  PROJECT_UPDATE: "PROJECT_UPDATE",
  PARTNERSHIP: "PARTNERSHIP",
  IMPACT: "IMPACT",
} as const;
